SUPABASE_URL = "https://qgbyverabqyngxwtrqra.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnYnl2ZXJhYnF5bmd4d3RycXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2MjIxMzEsImV4cCI6MjA1MjE5ODEzMX0.Q3Qs0C67G9P2m4QHBmDTLu-atlQ9LUlWk236uP92td4"
